//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coches
    {
        public Coches()
        {
            this.Formaciones_X_Coches = new HashSet<Formaciones_X_Coches>();
        }
    
        public int Id { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> EsLocomotora { get; set; }
        public Nullable<int> TipoConsumo { get; set; }
        public Nullable<int> ConsumoMovimiento { get; set; }
        public Nullable<int> ConsumoParado { get; set; }
        public int CantidadAsientos { get; set; }
        public int MaximoLegalPasajeros { get; set; }
        public int CapacidadMaximaPasajeros { get; set; }
    
        public virtual ICollection<Formaciones_X_Coches> Formaciones_X_Coches { get; set; }
    }
}
