//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_X_Incidentes
    {
        public int Id { get; set; }
        public int Id_Incidente { get; set; }
        public int Id_Estacion { get; set; }
    
        public virtual Estaciones Estaciones { get; set; }
        public virtual Incidentes Incidentes { get; set; }
    }
}
