//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formaciones_X_Coches
    {
        public int Id { get; set; }
        public int Id_Formacion { get; set; }
        public int Id_Coche { get; set; }
        public int VecesRepetido { get; set; }
    
        public virtual Coches Coches { get; set; }
        public virtual Formaciones Formaciones { get; set; }
    }
}
