//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formaciones
    {
        public Formaciones()
        {
            this.Formaciones_X_Coches = new HashSet<Formaciones_X_Coches>();
            this.Servicios_X_Formaciones = new HashSet<Servicios_X_Formaciones>();
        }
    
        public int Id { get; set; }
        public string NombreFormacion { get; set; }
    
        public virtual ICollection<Formaciones_X_Coches> Formaciones_X_Coches { get; set; }
        public virtual ICollection<Servicios_X_Formaciones> Servicios_X_Formaciones { get; set; }
    }
}
