//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ffccSimulacionEntities : DbContext
    {
        public ffccSimulacionEntities()
            : base("name=ffccSimulacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coches> Coches { get; set; }
        public virtual DbSet<Estaciones> Estaciones { get; set; }
        public virtual DbSet<Estaciones_X_Incidentes> Estaciones_X_Incidentes { get; set; }
        public virtual DbSet<Formaciones> Formaciones { get; set; }
        public virtual DbSet<Formaciones_X_Coches> Formaciones_X_Coches { get; set; }
        public virtual DbSet<Incidentes> Incidentes { get; set; }
        public virtual DbSet<Relaciones> Relaciones { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Servicios_X_Formaciones> Servicios_X_Formaciones { get; set; }
        public virtual DbSet<Simulaciones> Simulaciones { get; set; }
        public virtual DbSet<Trazas> Trazas { get; set; }
        public virtual DbSet<Trazas_X_Servicios> Trazas_X_Servicios { get; set; }
    }
}
