//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones
    {
        public int Id { get; set; }
        public int Id_Estacion_Anterior { get; set; }
        public int Id_Estacion_Siguiente { get; set; }
        public int Id_Servicio { get; set; }
        public int Distancia { get; set; }
        public int VelocidadPromedio { get; set; }
        public int TiempoViaje { get; set; }
        public int Est_Sig_Es_Parada { get; set; }

        /*Asumi que esta es la estacion origen. TODO: verificar que sea asi*/
        public virtual Estaciones Estaciones { get; set; }
        
        /*Asumi que esta es la estacion destino. TODO: verificar que sea asi*/
        public virtual Estaciones Estaciones1 { get; set; }
        public virtual Servicios Servicios { get; set; }


        public bool relaciona(Estaciones nodoInicial, Estaciones nodoFinal)
        {
            //TODO Revisar si la relacion es bidireccional.
            if ((Id_Estacion_Anterior == nodoInicial.Id && Id_Estacion_Siguiente == nodoFinal.Id) || (Id_Estacion_Anterior == nodoFinal.Id && Id_Estacion_Siguiente == nodoInicial.Id))
            {
                return true;
            }
            return false;
        }

        public int calcularTiempoViaje()
        {
            //TODO Modificar
            return TiempoViaje;
        }

        public int demoraPorAccidentes()
        {
            int totalDemora = 0;
            foreach (Incidentes incidentePosible in Estaciones1.ListaIncidentes)
            {
                if (incidentePosible.Ocurre())
                {
                    totalDemora += incidentePosible.TiempoDemora;
                }
            }
            return totalDemora;
        }
    }
}
