//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public Servicios()
        {
            this.Relaciones = new HashSet<Relaciones>();
            this.Servicios_X_Formaciones = new HashSet<Servicios_X_Formaciones>();
            this.Trazas_X_Servicios = new HashSet<Trazas_X_Servicios>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Relaciones> Relaciones { get; set; }
        public virtual ICollection<Servicios_X_Formaciones> Servicios_X_Formaciones { get; set; }
        public virtual ICollection<Trazas_X_Servicios> Trazas_X_Servicios { get; set; }
    }
}
