//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulaciones
    {
        public int Id { get; set; }
        public int Tiempo_Inicial { get; set; }
        public int Tiempo_Final { get; set; }
        public int Id_Traza { get; set; }
        public int Frecuencia_Salida { get; set; }
        public string Nombre { get; set; }
    
        public virtual Trazas Trazas { get; set; }
    }
}
